version: '3.3'

services:
  django-app:
    build: .
    container_name: django-app
    restart: always
    volumes:
      - static-files:/usr/src/static/:rw
      - db:/usr/src/static/db.sqlite3:rw
    networks:
      - backend
    ports:
      - 3000:3000
    env_file:
      - local.env

  web:
    image: nginx:1.21.5-alpine
    container_name: web
    restart: always
    volumes:
      - static-files:/usr/share/nginx/static/:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend
      - frontend
    ports:
      - 80:80
    depends_on:
      - django-app

volumes:
  static-files:
  db:

networks:
  frontend:
  backend:
