version: '3.3'

services:
  django-app:
    user: "1000:1000"
    build: .
    container_name: django-app
    restart: always
    volumes:
      - static-files:/usr/src/app/static/:rw
      - db:/usr/src/app/db/:rw
    networks:
      - backend
    ports:
      - 8000:8000
    env_file:
      - local.env
    environment:
      - DJANGO_STATIC_ROOT=/usr/src/app/static/
      - DATABASE_FILE=/usr/src/app/db/db.sqlite3
    # NOTICE: target folders will be
    #    /usr/src/app
    #    /usr/src/app/db - mounted
    #    /usr/src/app/static - mounted

  web:
    image: nginx:1.21.5-alpine
    container_name: web
    restart: always
    volumes:
      - static-files:/usr/share/nginx/static/:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend
      - frontend
    ports:
      - 80:80
    depends_on:
      - django-app

volumes:
  static-files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: static
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: db

networks:
  frontend:
  backend:
