# Generated by Django 4.0.4 on 2022-04-22 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_code', models.CharField(default='', max_length=255)),
                ('_total_real_space', models.FloatField(null=True)),
                ('users_and_weights', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.BigIntegerField(default=-1)),
                ('options', models.TextField(default='{}')),
                ('question', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(default=-716321959)),
                ('title', models.CharField(default='[unknown]', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tbot.poll')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('personal_chat_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tbot.estate')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tbot.section'),
        ),
        migrations.CreateModel(
            name='Eossstats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tbot.estate')),
                ('poll', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tbot.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('options', models.TextField(default='{}')),
                ('question', models.TextField(default='')),
                ('target_section', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tbot.section')),
            ],
        ),
    ]
