# Generated by Django 4.0.4 on 2022-04-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0002_vote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_chat_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
