# Generated by Django 4.0.4 on 2022-04-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0004_alter_user_estate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='selected_vote',
            field=models.TextField(default=''),
        ),
    ]
