# Generated by Django 4.0.4 on 2022-04-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0005_vote_selected_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='selected_vote_id',
            field=models.IntegerField(default=-1),
        ),
    ]
