# Generated by Django 4.0.4 on 2022-04-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0008_remove_user_estate_delete_eossstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estateowning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owning_weight', models.FloatField(null=True)),
                ('estate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tbot.estate')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tbot.user')),
            ],
        ),
    ]
