# Generated by Django 4.0.4 on 2022-04-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0009_estateowning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estateowning',
            old_name='estate_id',
            new_name='estate',
        ),
        migrations.RenameField(
            model_name='estateowning',
            old_name='user_id',
            new_name='user',
        ),
    ]
