# Generated by Django 4.0.4 on 2022-04-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0010_rename_estate_id_estateowning_estate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='personal_chat_id',
        ),
    ]
