# Generated by Django 4.0.4 on 2022-04-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0011_remove_user_personal_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='users_and_weights',
        ),
    ]
