# Generated by Django 4.0.4 on 2022-05-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0013_user_dialog_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dialog_state',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
