@startuml

start

:пользователь инициирует личный разговор с ботом **/start**;

partition #pink "весь сет проверок" {
switch (что за пользователь?)
    case(появился впервые)
        : заводим его в бд со всей инфой;
        : сообщаем пользователю, что он не верифицирован и сообщаем, что будем проходить верификацию;
        #palegreen :сценарий верификации — пользователь указывает свои объекты недвижимости и запрос уходит на аппрув админу;
        #palegreen :после аппрува приходит сообщение от бота "вы заапрувлены";
    case(есть в базе, но не заапрувлен)
        : сообщаем пользователю, что он не верифицирован и сообщаем, что будем проходить верификацию;
        #palegreen :сценарий верификации — пользователь указывает свои объекты недвижимости и запрос уходит на аппрув админу;
        #palegreen :после аппрува приходит сообщение от бота "вы заапрувлены";
    case(есть в базе, заявка на аппрув отправлена)
        : сообщаем пользователю, что мы его знаем и его вот-вот заапрувит админ. И контакты для экстренной связи;
        #palegreen :после аппрува приходит сообщение от бота "вы заапрувлены";
    case(заапрувленный пользователь)
        : приветствуем, говорим что мы его уже знаем как собственника;
endswitch

}

#green :приходит основное меню;

switch (что хочет сделать пользователь?)
    case(запустить ЭОСС)
        #pink : проводим весь сет проверок как при /start\nи не идём дальше если не закончим;
        : даём инструкцию как это работает;
        partition #palegreen "сценарий запуска ЭОСС"{
            : получаем опрос;
            : выясняем в какой секции запускать;
            : запускаем опрос уже в группе секции;
            #lightblue :приём голосов идёт уже в группе секции;
        }
    case(посмотреть результаты запущенных ранее опросов)
        #pink : проводим весь сет проверок как при /start\nи не идём дальше если не закончим;
        partition #palegreen "сценарий показа результатов"{
        : делаем все расчёты;
        : показываем пользователю результаты расчётов;
        }
    case(посмотреть свои объекты недвижимости)
        #pink : проводим весь сет проверок как при /start\nи не идём дальше если не закончим;
        :показываем объекты недвижимости,\nпроцент владения,\nкто ещё с ним вместе ими владеет;
    case(изменить свои объекты недвижимости)
        #pink : проводим весь сет проверок как при /start\nи не идём дальше если не закончим;
        : предлагаем связаться с админом, чтобы тот ручками поправил;
endswitch

#green :приходит основное меню;

end

@enduml