#
#  На данный момент забили на
#  1. Пуш в какой-то регистри — нахуй
#  2. Stateless — нахуй
#         В перспективе надо вытащить базу из sqlite в какой-то внешнюю базку
#         И тогда один контейнер с python надо разбить на два: отдельно бот, отдельно веб-аппка - и обе общаются с внешней базкой
#

# TODO: отделить сценарии для прода и для теста
# TODO: прогнать автотесты перед деплоем в прод!
# TODO: миграции
name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build_python:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v3
    - name: "Env file"
      run: env > local.env
    - name: "Build new container"
      run: docker-compose build

  deploy_python:
    runs-on: [self-hosted, linux]
    needs: build_python
    steps:
    - uses: actions/checkout@v3
    - name: "Stop all running containers"
      run: docker-compose down
    - name: "Run new"
      run: docker-compose up -d
#
#  # This workflow contains a single job called "build"
#  debug:
#    # The type of runner that the job will run on
#    runs-on: [self-hosted, linux]
#    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v3
#      - name: Run a one-line script
#        run: echo Hello, world!
#      - name: Check where are we?
#        run: |
#          whoami
#          pwd
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,

